name: Workflow for our actions
 
on: [push]
 
jobs:
  run-javascript-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: installl dependencies
        run:  npm install @actions/github 
 
      - name: JavaScript repeat action
        uses: jmmirand/clean-workflows-logs-runs@v1
        with:
         myToken: ${{ secrets.GITHUB_REPO_TOKEN }}
         num_runs: 12

